name: cloudmusic
version: 1.0.0+1
publish_to: none
description: A new Flutter Music
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.6.0
  flutter_swiper_view: ^1.1.8
  dio: ^4.0.6
  cached_network_image: ^3.2.2
  easy_refresh: ^3.0.5+1
  audioplayers: ^1.1.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.15
  flutter_staggered_animations: ^1.1.1
  video_player: ^2.4.8
  chewie: ^1.3.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # 配置图标
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/tabsIcon/iconfont.ttf
